spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-shop-config-dev
---
spring:
  profiles: test
  application:
    name: spring-cloud-shop-config-test
